### PR TITLE
Add support for official Python & Django versions

### PR DESCRIPTION
**Pull request by irtazaakram**
Hi @jpic @yourlabsopensource,

I've made this PR to 

- Add support for Django 3.2, 4.1 & 4.2
- Add support for Python 3.8, 3.9, 3.10 & 3.11
- Drop support for Django 1.11, 2.1, 2.2 & 3.0
- Drop support for Python 2.7, 3.5, 3.6 & 3.7
- Shifted CI from travis/gitlab to github actions

Please can we have a new release after this PR is merged.

Thanks,

### CODE REVIEW

**Comment by awais786** [comment]
Thanks for this pr.

**Comment by awais786** [comment]
@jpic any chance to merge this PR and release it.

**Comment by jpic** [comment]
Sorry, I recently fixed a mailbox configuration that was preventing all GitHub emails from showing up to me.

**Comment by stefan6419846** [comment]
This PR removed GitLab CI completely. I am not sure if this is the intended situation given the linked discussion on the old project.

**Pull request merged**
